controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - motor1
      - motor2
      - motor3
      - motor4
      - motor5
      - motor6
